# Generated by Django 4.1.1 on 2022-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha', models.DateField(verbose_name='Fecha Ingreso')),
            ],
        ),
    ]
